version: "2"

networks:
  ota_network:
    driver: bridge

volumes:
  ota_elasticsearch_data:
  ota_postgres_data:


services:
  elasticsearch:
    restart: always
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ingress=[{"type":"append"},{"type":"bytes"},{"type":"convert"},{"type":"date"},{"type":"date_index_name"},{"type":"dissect"},{"type":"dot_expander"},{"type":"drop"},{"type":"fail"},{"type":"foreach"},{"type":"geoip"},{"type":"grok"},{"type":"gsub"},{"type":"join"},{"type":"json"},{"type":"kv"},{"type":"lowercase"},{"type":"pipeline"},{"type":"remove"},{"type":"rename"},{"type":"script"},{"type":"set"},{"type":"sort"},{"type":"split"},{"type":"trim"},{"type":"uppercase"},{"type":"urldecode"},{"type":"user_agent"}]
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ota_elasticsearch_data:/usr/share/elasticsearch/ota-data
    networks:
      - ota_network
  kibana:
    restart: always
    container_name: kibana
    image: docker.elastic.co/kibana/kibana-oss:6.8.2
    ports:
      - "5601:5601"
    environment:
      - LOGGING_VERBOSE=true
    depends_on:
      - elasticsearch
    networks:
      - ota_network
  postgres:
    container_name: postgres
    build: ./postgres-ota
    image: postgres:10-ota
    restart: always
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=postgres
#      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
    volumes:
#      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ota_postgres_data:/var/lib/postgresql/data
    networks:
      - ota_network


